# -------- TPM (DEVE ESSERE PRIMO SOLO COME PLUGIN, MA CARICATO PER ULTIMO) --------
set -g @plugin 'tmux-plugins/tpm'

# -------- PLUGINS --------
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# -------- CONTINUUM --------
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# -------- HISTORY --------
set -g history-limit 50000

# -------- PREFIX --------
unbind C-b
set -g prefix `
bind-key ` last-window
bind-key e send-prefix

# -------- KEYBOARD / EXTENDED KEYS --------
set -g backspace C-?
set -s extended-keys always
set -as terminal-features ',xterm*:extkeys'
set -g allow-passthrough on
set -g xterm-keys on

# -------- WINDOWS / RENUMBER --------
set -g renumber-windows on
set -g base-index 1

# -------- VI MODE --------
set -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
set -g mouse on

# -------- STATUS BAR --------
set -g status-bg black
set -g status-fg white
set -g status-left "[#S] "
set -g status-right "%H:%M | %d-%m-%Y"

# -------- WINDOW TAB STYLE (like browser tabs) --------
set -g window-status-style "fg=#666666,bg=default"
set -g window-status-format " #I:#W "
set -g window-status-current-style "bg=#ff8700,fg=#000000,bold"
set -g window-status-current-format " #I:#W "
set -g window-status-separator "|"

# -------- INIT TPM (DEVE ESSERE ULTIMA RIGA ASSOLUTA) --------
run '~/.tmux/plugins/tpm/tpm'
